spring.application.name=cosmo-cats-intergalactic-marketplace

spring.liquibase.change-log=classpath:liquibase/changelog.yaml

spring.datasource.url=jdbc:postgresql://localhost:5432/cosmo_cats_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate




